title:  Definition of clinically distinct molecular subtypes in estrogen receptor positive breast carcinomas using genomic grade (GSE6532 U133A)
featureDescription:  gene
featureDescriptionPlural:  genes
