title:  Gene expression classification of colon cancer defines six molecular subtypes with distinct clinical, molecular and survival characteristics (GSE39582)
featureDescription:  gene
featureDescriptionPlural:  genes
