title:  Global changes in gene expression of Barret'''s esophagus compared to normal squamous esophagus and gastric cardia tissue (GSE39491)
featureDescription:  gene
featureDescriptionPlural:  genes
