title:  Global changes in gene expression of Barrett's esophagus compared to normal squamous esophagus and gastric cardia tissues (GSE39491) 
featureDescription:  gene
featureDescriptionPlural:  genes
