title:  Molecular signature with high accuracy for biliary atresia identifies a role for Interleukin-8 in pathogenesis of disease (GSE46995)
featureDescription:  gene
featureDescriptionPlural:  genes
