title:  Bronchial airway gene expression reflects a COPD-associated field of injury that changes with disease severity and is reversible with therapy (GSE37147)
featureDescription:  gene
featureDescriptionPlural:  genes
