title:  A Gene expression-based blood diagnostic for symptomatic transthyretin amyloidosis revealing male and female-specific signatures (GSE67784)
featureDescription:  gene
featureDescriptionPlural:  genes
