title:  Biomarker discovery in non-small cell lung cancer: integrating gene expression profiling, meta-analysis and tissue microarray validation (GSE37745)
featureDescription:  gene
featureDescriptionPlural:  genes
