title:  MRE11 deficiency increases sensitivity to Poly(ADP-ribose) polymerase inhibition in microsatellite unstable colorectal cancers (GSE26682 U133PLUS2)
featureDescription:  gene
featureDescriptionPlural:  genes
